In [36]:
import pandas as pd

In [37]:
avocado=pd.read_csv(r"C:\Users\Yuliia.Petrenko\OneDrive - Three60Energy\Working File Cloud\HR\L\Avocado\avocado.csv",sep = '\t')
avocado.head()

,code,lc,product_name_de,product_name_el,product_name_en,product_name_es,product_name_fi,product_name_fr,product_name_id,product_name_it,...,off:ecoscore_data.adjustments.packaging.non_recyclable_and_non_biodegradable_materials,off:ecoscore_data.adjustments.production_system.value,off:ecoscore_data.adjustments.threatened_species.value,sources_fields:org-database-usda:available_date,sources_fields:org-database-usda:fdc_category,sources_fields:org-database-usda:fdc_data_source,sources_fields:org-database-usda:fdc_id,sources_fields:org-database-usda:modified_date,sources_fields:org-database-usda:publication_date,data_sources
0,0059749979702,fr,NaN,NaN,NaN,NaN,NaN,Naturalia Avocado Oil,NaN,NaN,...,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"App - yuka, Apps"
1,7610095131409,en,NaN,NaN,NaN,NaN,NaN,Avocado Bowl chips,NaN,NaN,...,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"App - Yuka, Apps, Producers, Producer - zweifel"
2,4005514005578,en,NaN,NaN,Gelbe Linse Avocado Brotaufstrich,NaN,NaN,NaN,NaN,NaN,...,1.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"App - yuka, Apps, App - smoothie-openfoodfacts"
3,0879890002513,en,NaN,NaN,Avocado toast chili lime,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"App - Yuka, Apps, App - InFood"
4,0223086613685,en,NaN,NaN,Avocado,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"App - Yuka, Apps"

In [38]:
#Subsetting large DataFrame
relevant_columns = ['code', 'lc', 'product_name_en', 'quantity', 'serving_size', 'packaging_tags', 'brands', 'brands_tags', 'categories_tags', 'labels_tags', 'countries', 'countries_tags', 'origins','origins_tags']
avocado=avocado[relevant_columns]
avocado.head()

,code,lc,product_name_en,quantity,serving_size,packaging_tags,brands,brands_tags,categories_tags,labels_tags,countries,countries_tags,origins,origins_tags
0,0059749979702,fr,NaN,NaN,NaN,NaN,Naturalia,naturalia,"en:plant-based-foods-and-beverages,en:plant-ba...",NaN,Canada,en:canada,NaN,NaN
1,7610095131409,en,NaN,NaN,NaN,NaN,Zweifel,zweifel,"en:snacks,en:salty-snacks,en:appetizers,en:chi...","en:vegetarian,en:vegan","Switzerland, World","en:switzerland,en:world",NaN,NaN
2,4005514005578,en,Gelbe Linse Avocado Brotaufstrich,NaN,NaN,NaN,Tartex,tartex,de:abendbrotsufstrich,"en:organic,en:eu-organic,en:eg-oko-verordnung",Germany,en:germany,NaN,NaN
3,0879890002513,en,Avocado toast chili lime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,en:united-states,NaN,NaN
4,0223086613685,en,Avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,en:united-states,NaN,NaN

In [39]:
 
with open(r"C:\Users\Yuliia.Petrenko\OneDrive - Three60Energy\Working File Cloud\HR\L\Avocado\relevant_avocado_categories.txt", "r") as file:
    relevant_avocado_categories = file.read().splitlines()
    file.close()
relevant_avocado_categories

['en:avocadoes',
 'en:avocados',
 'en:fresh-foods',
 'en:fresh-vegetables',
 'en:fruchte',
 'en:fruits',
 'en:raw-green-avocados',
 'en:tropical-fruits',
 'en:tropische-fruchte',
 'en:vegetables-based-foods',
 'fr:hass-avocados']

In [40]:
#Filter avocado data using relevant category tags
avocado['categories_tags']=avocado['categories_tags'].str.split(',')
avocado.head()

,code,lc,product_name_en,quantity,serving_size,packaging_tags,brands,brands_tags,categories_tags,labels_tags,countries,countries_tags,origins,origins_tags
0,0059749979702,fr,NaN,NaN,NaN,NaN,Naturalia,naturalia,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Canada,en:canada,NaN,NaN
1,7610095131409,en,NaN,NaN,NaN,NaN,Zweifel,zweifel,"[en:snacks, en:salty-snacks, en:appetizers, en...","en:vegetarian,en:vegan","Switzerland, World","en:switzerland,en:world",NaN,NaN
2,4005514005578,en,Gelbe Linse Avocado Brotaufstrich,NaN,NaN,NaN,Tartex,tartex,[de:abendbrotsufstrich],"en:organic,en:eu-organic,en:eg-oko-verordnung",Germany,en:germany,NaN,NaN
3,0879890002513,en,Avocado toast chili lime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,en:united-states,NaN,NaN
4,0223086613685,en,Avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,en:united-states,NaN,NaN

In [42]:
#Dropping rows with null values in a particular column
avocado = avocado.dropna(subset = 'categories_tags')
avocado.head()

,code,lc,product_name_en,quantity,serving_size,packaging_tags,brands,brands_tags,categories_tags,labels_tags,countries,countries_tags,origins,origins_tags
0,0059749979702,fr,NaN,NaN,NaN,NaN,Naturalia,naturalia,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Canada,en:canada,NaN,NaN
1,7610095131409,en,NaN,NaN,NaN,NaN,Zweifel,zweifel,"[en:snacks, en:salty-snacks, en:appetizers, en...","en:vegetarian,en:vegan","Switzerland, World","en:switzerland,en:world",NaN,NaN
2,4005514005578,en,Gelbe Linse Avocado Brotaufstrich,NaN,NaN,NaN,Tartex,tartex,[de:abendbrotsufstrich],"en:organic,en:eu-organic,en:eg-oko-verordnung",Germany,en:germany,NaN,NaN
5,3662994002063,fr,NaN,3 fruits,NaN,NaN,la compagnie des fruits mûrs,la-compagnie-des-fruits-murs,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
6,8437013031011,fr,NaN,1 kg,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN

In [50]:
#Filtering a DataFrame based on a column of lists
avocado=avocado[avocado['categories_tags'].apply(lambda x:any([i for i in x if i in relevant_avocado_categories]))]
avocado.head(50)

,code,lc,product_name_en,quantity,serving_size,packaging_tags,brands,brands_tags,categories_tags,labels_tags,countries,countries_tags,origins,origins_tags
5,3662994002063,fr,NaN,3 fruits,NaN,NaN,la compagnie des fruits mûrs,la-compagnie-des-fruits-murs,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
6,8437013031011,fr,NaN,1 kg,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
14,4016249238155,de,NaN,135g,100g,de:gläschen,Allos,allos,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:vegetarian,en:eu-organic,en:no-g...",Deutschland,en:germany,Europäische Union,en:european-union
17,8718963381532,de,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Deutschland,en:germany,NaN,NaN
23,8436002746707,es,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,España,en:spain,NaN,NaN
28,8718452180288,fr,NaN,NaN,NaN,NaN,Jumbo,jumbo,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Belgique,en:belgium,NaN,NaN
30,8710400164968,fr,NaN,NaN,NaN,NaN,Albert Heijn,albert-heijn,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:no-gluten,en:nl-bi...",Belgique,en:belgium,NaN,NaN
43,3700353617111,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:fr-bio-01,fr:ab-ag...",France,en:france,NaN,NaN
46,4388860482393,de,Avocado,NaN,NaN,NaN,REWE Bio,rewe-bio,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:eg-oko-verordnung",Deutschland,en:germany,NaN,NaN
47,5060199511652,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
61,2664520010109,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
62,8713807005636,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
64,4018905590058,de,NaN,1 Stück,NaN,en:bulk,Metro Chef,metro-chef,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Deutschland,en:germany,NaN,NaN
65,0756058853791,en,Bio Avocado,500g,NaN,NaN,ABC Fresh GmbH,abc-fresh-gmbh,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:es-eco-011-an",Germany,en:germany,Spain,en:spain
102,4311532216507,en,NaN,NaN,NaN,NaN,Edeka,edeka,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Germany,en:germany,Chile,en:chile
106,4046434029305,en,NaN,NaN,100G,en:frisch,Essreif,essreif,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,"Germany, Italy","en:germany,en:italy",NaN,NaN
107,7610632951347,fr,NaN,NaN,NaN,NaN,Naturaplan,naturaplan,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:ch-bio-006","France, Allemagne, Suisse","en:france,en:germany,en:switzerland",NaN,NaN
115,0033383401591,fr,NaN,1,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Canada,en:canada,NaN,NaN
210,4337185372414,de,NaN,NaN,NaN,NaN,Kaufland,kaufland,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Deutschland,en:germany,NaN,NaN
212,4045612009412,de,NaN,100g,NaN,NaN,Lornamead GmbH,lornamead-gmbh,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,Deutschland,en:germany,NaN,NaN
227,3700946302165,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:es-eco-003-an,fr:a...",France,en:france,NaN,NaN
258,3439496511405,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
259,3242860001606,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
260,8445509158630,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
261,8710400412151,en,Avocado,250 g,NaN,en:container,Albert Heijn,albert-heijn,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,"France, Netherlands","en:france,en:netherlands",NaN,NaN
262,8433771101959,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
263,8445509039151,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
264,3700353611492,fr,NaN,NaN,NaN,"en:tray,fr:film-en-plastique",NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
265,3661949040174,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,fr:ab-agriculture-bio...",France,en:france,NaN,NaN
266,3701272602400,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,fr:ab-agriculture-bio...",France,en:france,NaN,NaN
267,3700344618042,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
268,7291008022948,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
269,8718963182207,nl,Avocados,NaN,NaN,en:container,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,"Frankrijk, Nederland","en:france,en:netherlands",NaN,NaN
270,3332230016566,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
271,3411060009617,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:non-eu-agriculture...",France,en:france,NaN,NaN
272,3458462047243,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
273,3760187780375,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
274,3700353616473,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic",France,en:france,NaN,NaN
275,3700353611362,fr,NaN,NaN,NaN,"en:tray,fr:film-en-plastique",NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
276,3276559475676,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
277,8436008522435,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
278,3344840000194,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
279,00140478,fr,NaN,NaN,NaN,NaN,Marks & Spencer,marks-spencer,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
280,3700353614028,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,fr:ab-agriculture-bio...",France,en:france,NaN,NaN
281,3700389406970,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
282,3700946302172,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:es-eco-001-an,fr:a...",France,en:france,NaN,NaN
283,17572897,fr,NaN,3,NaN,en:net,Nosibe,nosibe,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,Mexique,en:mexico
284,3700353614448,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
285,8445509163900,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN
286,8433771211092,fr,NaN,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,France,en:france,NaN,NaN

In [51]:
#Where do most UK avocados come from?
#Filtering your DataFrame by a particular country
avocado_UK=avocado[avocado['countries']=='United Kingdom']
avocado_UK

,code,lc,product_name_en,quantity,serving_size,packaging_tags,brands,brands_tags,categories_tags,labels_tags,countries,countries_tags,origins,origins_tags
361,00985833,en,Avacado,650 g,NaN,NaN,Marks & Spencer,marks-spencer,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,Peru,en:peru
381,00040464,en,Avocado,NaN,NaN,NaN,NaN,NaN,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN
414,4088600100173,en,Avocado,100 g,NaN,en:mixed-plastic-unknown,Aldi,aldi,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN
468,01307351,en,Avacados organic,NaN,NaN,"en:card-tray,en:ldpe-bag",Sainsbury’s SO organic,sainsbury-s-so-organic,"[en:plant-based-foods-and-beverages, en:plant-...","en:organic,en:eu-organic,en:non-eu-agriculture...",United Kingdom,en:united-kingdom,NaN,NaN
508,5057172125395,en,Just Essentials Avocados,4pack,NaN,en:mixed-plastic-film-packet-to-recycle,Asda,asda,"[en:plant-based-foods-and-beverages, en:plant-...","en:class-i,en:contains-stones",United Kingdom,en:united-kingdom,Peru,en:peru
510,23066755,en,Ready to Eat Avocados,2,NaN,en:mixed-plastic-bag,Asda,asda,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,"Spain, Peru","en:spain,en:peru"
708,03201985,en,Avocado,2,80g,"en:mixed-plastic-packet,en:plastic-film",Tesco,tesco,"[en:plant-based-foods-and-beverages, en:plant-...","en:tesco-nurture,en:vitamin-e-source",United Kingdom,en:united-kingdom,"Chile, Peru","en:chile,en:peru"
781,10096369,en,Avocado,NaN,100 g,NaN,Tesco,tesco,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN
850,00184915,en,Rich & creamy avocados,NaN,NaN,"en:card-tray,en:mixed-plastic-sleeve",By Sainsbury's,by-sainsbury-s,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN
1190,01600322,en,Ripe & ready medium avocados,2,NaN,"en:card-tray,en:ldpe-bag",Sainsbury's,sainsbury-s,"[en:plant-based-foods-and-beverages, en:plant-...",en:class-i,United Kingdom,en:united-kingdom,Israel,en:israel
1301,5000128606387,en,Avocados,NaN,NaN,en:mixed-plastic-film-packet,Co op,co-op,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN
1413,2322725400995,en,Avocados,NaN,NaN,en:ldpe-bag,Morrisons,morrisons,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN
1771,5010251741985,en,Extra large avocado,1 avocado,NaN,NaN,Morrisons,morrisons,"[en:plant-based-foods-and-beverages, en:plant-...",NaN,United Kingdom,en:united-kingdom,NaN,NaN

In [72]:
#Counting and ordering by the unique values in the country of origin column
top_avocado_origin=avocado_UK.groupby('origins_tags').agg(top_count=('origins_tags','count')).nlargest(1,'top_count').index[0]
top_avocado_origin

'en:peru'

In [ ]:
#top_avocado_origin=avocado_UK['origins_tags'].value_counts().index[0]
#top_avocado_origin

'en:peru'

In [76]:
#Strip out characters before country name
top_avocado_origin=top_avocado_origin.lstrip('en:')
top_avocado_origin

'peru'

In [ ]:
###  define  and return the top origin country for that food item

def read_and_filter_data(filename, relevant_categories):
    df = pd.read_csv(
        rf"C:\Users\Yuliia.Petrenko\OneDrive - Three60Energy\Working File Cloud\HR\L\Avocado\{filename}",
        sep="\t"
    )
  
  # Subset large DataFrame to include only relevant columns
    subset_columns = [ 'code', 'lc', 'product_name_en', 'quantity', 'serving_size', 'packaging_tags', 'brands', 'brands_tags', 'categories_tags', 'labels_tags', 'countries', 'countries_tags', 'origins','origins_tags']
    df = df[subset_columns]

  # Split tags into lists
    df['categories_list'] = df['categories_tags'].str.split(',')

  # Drop rows with null categories data
    df = df.dropna(subset = 'categories_list')

  # Filter data for relevant categories
    df = df[df['categories_list'].apply(lambda x: any([i for i in x if i in relevant_categories]))]
    
  # Filter data for the UK
    df_uk = df[(df['countries']=='United Kingdom')]

  # Find top origin country string with the highest count
    top_origin_string = (df_uk['origins_tags'].value_counts().index[0])

  # Clean up top origin country string
    top_origin_country = top_origin_string.lstrip("en:")
    top_origin_country = top_origin_country.replace('-', ' ')

    print(f'**{filename[:-4]} origins**','\n', top_origin_country, '\n')

    print ("Top origin country: ", top_origin_country)
    print ("\n")

  # End of function - return top origin country for this ingredient
    return top_origin_country

In [82]:
# Analyze avocado origins again, this time by calling function
top_avocado_origin = read_and_filter_data('avocado.csv',relevant_avocado_categories)

**avocado origins**
 peru

Top origin country:  peru