In [2]:
import pandas as pd
from pathlib import Path

schools = pd.read_csv(Path("schools.csv"))
schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7

In [5]:
#Finding schools with the best math scores
best_math_schools=schools[schools['average_math']>=600]
best_math_schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
5,Bard High School Early College,Manhattan,M097,634,641,639,70.8
45,Eleanor Roosevelt High School,Manhattan,M855,641,617,631,86.0
68,"High School for Mathematics, Science, and Engi...",Manhattan,M812,683,610,596,92.6

In [10]:
# Identifying the top 10 performing schools
schools['total_SAT']=schools['average_math']+	schools['average_reading']+schools['average_writing']
top_10=schools.nlargest(10,'total_SAT').reset_index(drop=True)
top_10

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,Stuyvesant High School,Manhattan,M477,754,697,693,97.4,2144
1,Staten Island Technical High School,Staten Island,R440,711,660,670,99.7,2041
2,Bronx High School of Science,Bronx,X445,714,660,667,97.0,2041
3,High School of American Studies at Lehman College,Bronx,X905,669,672,672,91.8,2013
4,Townsend Harris High School,Queens,Q515,680,640,661,97.1,1981
5,Queens High School for the Sciences at York Co...,Queens,Q774,701,621,625,97.9,1947
6,Bard High School Early College,Manhattan,M097,634,641,639,70.8,1914
7,Brooklyn Technical High School,Brooklyn,K430,682,608,606,95.5,1896
8,Eleanor Roosevelt High School,Manhattan,M855,641,617,631,86.0,1889
9,"High School for Mathematics, Science, and Engi...",Manhattan,M812,683,610,596,92.6,1889

In [ ]:
# Locating the NYC borough with the largest standard deviation in SAT performance#